### ISSUE TITLE
Jovo to-do

### ISSUE THREAD

**Issue by Lawreros** [jovo/cv#103]
- [x] under journal service, start and end dates should be added, we'll need to sit together to do this
- [x] add way more stats about twitter (your twitter login isn't on bitwarden and I can't see any more significant stats than followers/following from the outside)
- [x] under consultancy, board, and startups, @jovo needs to add more detail.
- [x] GOAL of Project (JOVO, please provide info).
- [x] elaborate on your involvement with MedHacks (referenced under University Service)
- [x] add brief description for what each student did under "Undergraduate Student Supervision" section
- [x] Sort out CAREER funding entry ("Have you heard back on this? Cannot get this award if tenured. Sri indicates that you have 1 more shot (July 2020) but could be ineligible after you are promoted to Associate Editor.")
- [x] Specify which print journals the "Manuscripts in Preparation for Submission" are intended to be submitted too
 - [x] Elaborate on publications in which you had middle authorship and what you did for them (For papers for which you are in the middle, we would like to be able to explain your role within large multidisciplinary projects. We want your involvement in BIG projects to be a strength")

**Comment by jovo** [comment]
@Lawreros assigned twitter back to you :)

**Comment by jovo** [comment]
in prep manuscripts under review at:
mgc-x: submitted to JMLR
disrim: eLife
deep learning: Nature machine intelligence
sporf: JMLR
bagging: neuroimage
UF: about to be PAMI
mouse connectome: neuroimage
mgcpy: about to be JMLR
neurosubtypes: biological psychiatry
graph independence: about to be PAMI
cosie/mase: JMLR
LOL: about to be nature methods
zeyi's paper: Canadian Journal of Statistics
ndmg: about to be Nature Methods
signal subgraph: JASA
k-groups: PAMI

**Comment by jovo** [comment]
@Lawreros ignore the above comment.

manuscripts in "in prep for submission" that have not yet been submitted anywhere:

#12 audrey's article

that's it i think actually.
oh, please add fast dcorr, on arxiv now: https://arxiv.org/abs/1912.12150
it should be submitted this week anyway.

**Comment by jovo** [comment]
the order of sections should be:

1. In preparation for submission
2. Previously submitted
3. Accepted
4. Technical Reports
5. Other

thanks

ps - find the tech reports and others here: 
https://neurodata.io/research/

not sure when/why they fell off the cv.

thanks, j

**Comment by Lawreros** [comment]
Could you clarify the difference in "In preparation for submission" and "Previously submitted"?
So everything in "Previously submitted" should be the papers that are under review but not published yet? And everything in the "In preparation for submission" is whatever is left over (audrey, etc.)?
(I've been moving to a new place all day and will be flying out to Washington for the dmriprep sprint tomorrow, so I may be a little slow in addressing these)

**Comment by jovo** [comment]
there are only 2 in prep for submission, meaning on arxiv and not submitted yet.
